# Generated by Django 3.2.8 on 2021-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211123_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/default.png', null=True, upload_to='profile_picture/'),
        ),
    ]
