# Generated by Django 3.2.8 on 2021-11-27 10:33

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_picture/default.png', null=True, upload_to=user.models.get_file_path),
        ),
    ]
